name: Node.js
on: [push]
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node && Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      # - name: Install Dependencies && tar Project
      #   run: |
      #     npm install -g pnpm 
      #     pnpm install -P

      - name: SSH
        uses: ErenKrt/ssh-push@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          destination: "/home/archive.zip"
          scripts: |
            kill -9 $(lsof -t -i :7001)
            cd /home && rm -rf app
            mkdir /home/app
            unzip archive.zip -d /home/app && chmod -R 777 /home/app
            rm -rf archive.zip
            sudo -s && cd /home/app && pnpm install -P
            pnpm start
            