name: Node.js
on: 
  push:
    branches:
      - master
      - 'ci-**'
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node && Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      - name: Install Dependencies && tar Project
        run: |
          npm install -g pnpm 
          pnpm install -P
          tar -zcvf ../release.tgz ./

      - name: SSH
        uses: lycpan233/ssh-deploy-nodejs@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PEM }}
          source: "../release.tgz"
          destination: "/root/release.tgz"
          workdir: "/root"
          scripts: |
            kill -9 $(lsof -t -i :7001)
            rm -rf ./app && mkdir ./app
            tar -zxvf release.tgz -C /root/app && rm -rf release.zip
            sudo -s && source ~/.zshrc && cd /root/app && pnpm start