name: Node.js
on: [push]
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node && Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      # - name: Install Dependencies && tar Project
      #   run: |
      #     npm install -g pnpm 
      #     pnpm install -P

      - name: SSH
        uses: ErenKrt/ssh-push@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          destination: "~/archive.zip"
          scripts: |
            kill -9 $(lsof -t -i :7001)
            rm -rf ~/app && mkdir ~/app
            cd ~/app && unzip ~/archive.zip -d ~/app && rm -rf ~/archive.zip && rm -rf ~/app/node_modules
            sudo -s && source ~/.zshrc && cd ~/app && pnpm install -P && pnpm start 